### ISSUE TITLE
Issue with dependencies (version `CXXABI_1.3.8' not found)

### ISSUE THREAD

**Issue by marianaql** [jsxlei/SCALE#12]
Dear SCALE team,

I am currently trying to run SCALE, which has been successfully installed. However, it outputs the following error regarding version `CXXABI_1.3.8' not found by sklearn package (which is already updated), and I was wondering if you could help me with this.
Thank you very much in advance!

(base) [mq224@login-e-14 SCALE]$ python SCALE.py -d ../files/ -k 4 --impute 
Traceback (most recent call last):
  File "SCALE.py", line 25, in <module>
    from scale import SCALE
  File "/rds/project/bg200/rds-bg200-hphi-gottgens/users/mq224/project_atacseq/samples/Fernando/SLX18781_SINAB12/outs/cellRangerPeaks/SCALExscATACseq/SCALE/scale/__init__.py", line 16, in <module>
    from .model import *
  File "/rds/project/bg200/rds-bg200-hphi-gottgens/users/mq224/project_atacseq/samples/Fernando/SLX18781_SINAB12/outs/cellRangerPeaks/SCALExscATACseq/SCALE/scale/model.py", line 22, in <module>
    from sklearn.mixture import GaussianMixture
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/mixture/__init__.py", line 5, in <module>
    from .gaussian_mixture import GaussianMixture
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/mixture/gaussian_mixture.py", line 11, in <module>
    from .base import BaseMixture, _check_shape
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/mixture/base.py", line 13, in <module>
    from .. import cluster
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/cluster/__init__.py", line 6, in <module>
    from .spectral import spectral_clustering, SpectralClustering
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/cluster/spectral.py", line 16, in <module>
    from ..neighbors import kneighbors_graph
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/neighbors/__init__.py", line 16, in <module>
    from .nca import NeighborhoodComponentsAnalysis
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/neighbors/nca.py", line 22, in <module>
    from ..decomposition import PCA
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/decomposition/__init__.py", line 11, in <module>
    from .sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/decomposition/sparse_pca.py", line 11, in <module>
    from ..linear_model import ridge_regression
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/linear_model/__init__.py", line 26, in <module>
    from .logistic import (LogisticRegression, LogisticRegressionCV,
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/linear_model/logistic.py", line 23, in <module>
    from ..svm.base import _fit_liblinear
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/svm/__init__.py", line 13, in <module>
    from .classes import SVC, NuSVC, SVR, NuSVR, OneClassSVM, LinearSVC, \
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/svm/classes.py", line 4, in <module>
    from .base import _fit_liblinear, BaseSVC, BaseLibSVM
  File "/home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/svm/base.py", line 6, in <module>
    from . import libsvm, liblinear
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/mq224/anaconda3/install/lib/python3.7/site-packages/sklearn/svm/libsvm.cpython-37m-x86_64-linux-gnu.so)

**Comment by jsxlei** [comment]
It seems that your environment settings are incompatible with sklearn. You can setup a new python env via conda, then install SCALE
conda create -n SCALE python=3.6 pytorch
conda activate SCALE

git clone git://github.com/jsxlei/SCALE.git
cd SCALE
python setup.py install
